# Generated by Django 3.2.4 on 2021-07-04 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_opinion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appeal',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
