version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=appeal_db
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=zzz111
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/in_my_opinion
    ports:
      - "8000:8000"
    depends_on:
      - db